SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `ibrainmart` ;
CREATE SCHEMA IF NOT EXISTS `ibrainmart` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ibrianmart` ;
